### ISSUE TITLE
 Image Builder ability to create QCOW from declarative

### ISSUE THREAD

**Issue by eak13** [airshipit/images#1]
This will be a pivotal component of how we introduce NC customizations and evolution to Airship 2.0.

How will this work? How will it be declarative?

How can it separate rebuilding the root (thus all new .debs/etc) from introducing a targeted layer change (e.g. a NC release wants to target updating i40e, NOTHING ELSE.)

Some considerations:
- Should be same dockerfile for ephmeral iso & target image
- Should split concerns between building rootfs (during docker img build) and packaging (ie iso/qcow, cloud init injection, runtime config - eg partitioning etc) at runtime: both to reduce time, but more importantly to ensure a consistent 'promoteable' artifact
- Should bake in k8s reqs (ie no konfigadm/package install required during instantiation)
- Should allow additional scripts to be injected during runtime - ie i40e driver install
- Currently bash, but ansible would be better (re declarative comment above)
-- How would this declarative interface look?
-- What do we want to declare?
--- Ansible VARs yaml file?
--- Two of them:
---- Something that constructs root files system
----- defines packages
----- common config
---- Something that defines what to construct (e.g. iso, qcow2, etc)
----- would also need to be able to inject custom role for i40e etc.

**Comment by eak13** [comment]
Proposed change
Patchset https://review.opendev.org/#/c/730777 has been created to provide the ImageBuilder command set. It's currently supporting ubuntu based airship hosts.

**Comment by craiganderson** [comment]
Closing this as image-builder satisifies the criteria listed in this issue.
