### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by seaneagan** [airshipit/images#13]
**Problem description (if applicable)**
We currently have no release automation to:
* publish semver image tags to quay
* publish release notes

**Proposed change**
Add similar release automation to that of airshipctl/krm functions: https://github.com/airshipit/airshipctl/issues/354

I believe the current direction is to use a single version (git tag) for all images in this repo, rather than independent versions for each image.

**Comment by seaneagan** [comment]
https://review.opendev.org/c/airship/images/+/784161

**Comment by eak13** [comment]
@seaneagan can we close this one?

**Comment by seaneagan** [comment]
still need to do release notes automation

**Comment by eak13** [comment]
@seaneagan thanks. This was leftover from the other day before we had a chance to talk on Flight Plan. Understood.

**Comment by seaneagan** [comment]
I think the plan for now is to only version the directly user facing components (airshipctl, treasuremap), so closing this.
