### ISSUE TITLE
Mirror dockerhub images to quay.io

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/images#14]
Docker hub ratelimiting continues to be a thorn in our side.  Our reference manifests now only point to a few remaining images in dockerhub.

This issue is to add a job to the Jenkins in the STL lab to effectively mirror the images in our remaining dockerhub registries into quay.io/airshipit.  This could be done periodically (e.g. nightly) or could be triggered by changes to the dockerhub registries, if that's doable.

The versions.yamls in airshipctl and treasuremap should be updated to to point to the quay.io mirrors as part of this issue.

**Comment by sreejithpunnapuzha** [comment]
commit for alpine image: https://review.opendev.org/c/airship/images/+/788062

**Comment by sreejithpunnapuzha** [comment]
all commits for this issue can be found with this url https://review.opendev.org/q/topic:%22dockerhub-quayio%22+(status:open%20OR%20status:merged)

**Comment by sreejithpunnapuzha** [comment]
All images which are currently pulled from dockerhub have been moved to quay. All commits relating to this have been merged. hence closing this issue
