### ISSUE TITLE
Enhance helm-chart-collator to authenticate with private git repos

### ISSUE THREAD

**Issue by mattmceuen** [airshipit/images#15]
Today, helm-chart-collator can collate charts from open git source repos, but not from ones that require authentication.  This issue is to add authentication capabilities.

The underlying ansible library used for git operations supports authentication already, so this should be a straightfoward change to the collator.

**Comment by ian-howell** [comment]
I guess the bot isn't working; PS here: https://review.opendev.org/c/airship/images/+/788959
