### ISSUE TITLE
Images with latest tag are not being pushed to quay

### ISSUE THREAD

**Issue by teoyaomiqui** [airshipit/images#17]
**Describe the bug**
The publish [job](https://zuul.opendev.org/t/openstack/builds?job_name=airship-images-publish) isn't using only images tagged with commit hash

**Steps To Reproduce**
Check latest updated tags of images in quay.io

**Expected behavior**
New images with tags latest-... appear with quay.io with each newly merged commit

**Possible cause**
It appears that the job name has to be unique in gate definition.
https://github.com/airshipit/images/blob/master/.zuul.yaml#L39-L42

**Comment by seaneagan** [comment]
Fixed here: https://review.opendev.org/c/airship/images/+/786955
