### ISSUE TITLE
Create Customized Ironic Images for Airship 2.0

### ISSUE THREAD

**Issue by eak13** [airshipit/images#2]
Incorporate required customization into local Airship ironic images. 

Example provided by @sb464f 
[ironic customization.txt](https://github.com/airshipit/images/files/4780694/ironic.customization.txt)

**Comment by sreejithpunnapuzha** [comment]
PS https://review.opendev.org#/c/753370/. This contains the loci based image build as well as the dependency images.

**Comment by sreejithpunnapuzha** [comment]
Commit https://review.opendev.org#/c/753370/ has been merged and images are getting published to quay.io. So closing the issue.
