### ISSUE TITLE
Complete Move of Image Builder to New image-builder Repository

### ISSUE THREAD

**Issue by lb4368** [airshipit/images#22]
**Proposed change**
Upon completion of https://github.com/airshipit/image-builder/issues/1 which sets up the Image Builder code and associated gating in the new _image-builder_ repository, the latest image builder updates need to be pulled into the new repository and the image builder code removed from this _images_ repository so that all future Image Builder work is done in the new repository.

**Comment by DannyMassa** [comment]
Assign to me please

**Comment by DannyMassa** [comment]
This PS just merged and should close this issue:

https://review.opendev.org/c/airship/images/+/802591

thanks!

**Comment by eak13** [comment]
closing per merge.
