### ISSUE TITLE
Images publishing is broken, Zuul jobs running out of space

### ISSUE THREAD

**Issue by seaneagan** [airshipit/images#23]
**Describe the bug**

The airship/images publishing jobs have been failing due to running out of space on the build VMs:

https://zuul.openstack.org/builds?job_name=airship-images-publish-commit
https://zuul.openstack.org/builds?job_name=airship-images-publish-latest

Hopefully moving the image builder to its own repo should allow the builds to fit tempoararily: #22 

If we add more images in the future though we may be back in the same situation. A more permanent solution may be to create individual Zuul jobs per image, and only run each job when the code for that image changes using:
https://zuul-ci.org/docs/zuul/reference/job_def.html?highlight=irrelevant#attr-job.files

We could probably then undo the change to split latest vs commit publish jobs as a per image split should be granular enough:
https://review.opendev.org/c/airship/images/+/784703
https://review.opendev.org/c/airship/images/+/786955

**Expected behavior**

Image publishing jobs do not run out of space, so that the images get automatically published after each change to their source code.

**Comment by lb4368** [comment]
This issue seems resolved as the image publishing jobs have been working for the last month or so.  Will reopen if necessary.
