### ISSUE TITLE
Create reference implementation to build and push a Helm-Chart Collator image

### ISSUE THREAD

**Issue by eak13** [airshipit/images#7]
As an Airship user, I want to have a working example of the tooling needed to build & push a Helm-Chart Collator image for the Airship-Core type in Treasuremap, so that I have a solid foundation upon which to build HCC images for my own implementation needs.

Could leverage https://github.com/airshipit/images/blob/master/helm-chart-collator/examples/charts.yaml as the basis of the image definition.

**Comment by michaelfix** [comment]
@sshiba - Sidney, is there an update?  Are we getting close(r) to finishing this issue?

**Comment by sshiba** [comment]
The https://review.opendev.org/c/airship/images/+/774028 implementing this issue was ready for review for a while. Have posted twice the request to review it. Sent again request over slack.

**Comment by sshiba** [comment]
The patchset [https://review.opendev.org/c/airship/images/+/774028](https://review.opendev.org/c/airship/images/+/774028) is currently being merged.

**Comment by sshiba** [comment]
https://review.opendev.org/c/airship/images/+/782583 has been merged.
This issue can be closed.

**Comment by lb4368** [comment]
Closed per patchsets merge
